### ISSUE TITLE
Rails 7 deprecated use of sum

### ISSUE THREAD

**Issue by machty** [shioyama/mobility-ransack#21]
On Rails 7 I'm getting deprecation errors:

```
DEPRECATION WARNING: Rails 7.0 has deprecated Enumerable.sum in favor of Ruby's native implementation available since 2.4. Sum of non-numeric elements requires an initial argument. (called from visit_collection at /home/travis/build/FutureProofRetail/business-server/vendor/bundle/ruby/3.1.0/gems/mobility-ransack-1.1.0/lib/mobility/ransack.rb:15)
```

Issue seems to be [here](https://github.com/shioyama/mobility-ransack/blob/master/lib/mobility/ransack.rb#L15); to fix, you'll need to pass add an argument into sum; I'd put in a PR but I'm not sure what that arg should be.

**Comment by mhenrixon** [comment]
Having the same issue, any help greatly appreciated @shioyama!
