### ISSUE TITLE
Any chance to release a new version?

### ISSUE THREAD

**Issue by tagliala** [shioyama/mobility-ransack#28]
Hi, would it be possible to release a new version with the latest changes on master branch?

That would allow to update the ransack dependency to 3.x

I've also created:
- #27
- #29
- #30

**Comment by tagliala** [comment]
Hi, this is a friendly bump for the merge of the aforementioned PRs

I will then proceed to check against Ransack main and add compatibility for 4.0, because of activerecord-hackery/ransack#1400 and a potential security issue (information disclosure)

Quoting from https://owasp.org/Top10/A01_2021-Broken_Access_Control/

> A01:2021-Broken Access Control is the category with the most serious web
application security risk.

Allowing all attributes violates the principle of least privilege or deny by default,
where access should only be granted for particular capabilities, roles, or users.

**Comment by shioyama** [comment]
Sorry for taking so long, I've released 1.2.2!

**Comment by tagliala** [comment]
Thanks for the release, I will make a new PR to improve the changelog
