### ISSUE TITLE
Issue with form helpers

### ISSUE THREAD

**Issue by gentlemich** [shioyama/mobility-ransack#33]
Hello!

I'm using Ransack form helpers to perform searches on models:
`<%= search_form.search_field :title_cont, class: 'form-control', placeholder: 'Name' %>`

Unfortunately, that returns an error
`undefined method title_cont' for Ransack::Search<class: Training, base: Grouping <combinator: and>>:Ransack::Search`

Here is my controller:
```
def index
    @search = @trainings.i18n.ransack(params[:q])
    @trainings = @search.result(distinct: true)
  end
```

I'm on Rails 7.0.4.3, Ruby 3.2.2 with mobility, mobility-ransack and ransack 4 installed.

**Comment by madhums** [comment]
Having the same issue after upgrading mobility-ransack to `1.2.2`. Would you mind sharing the reason for closing this?

**Comment by gentlemich** [comment]
Hi @madhums 
I forgot to allow the parameters in my model using `ransackable_attributes`

**Comment by madhums** [comment]
Umm are you really sure? I am having the same error but I have defined it properly. Would you mind having a look at https://github.com/shioyama/mobility-ransack/issues/34?

**Comment by madhums** [comment]
nvm, there's a syntax issue! 🙄
