### ISSUE TITLE
Ransack version dependency 

### ISSUE THREAD

**Issue by petewalker** [shioyama/mobility-ransack#5]
I'm running into some trouble getting Ransack to work with Rails 5.2.2 (see https://github.com/activerecord-hackery/ransack/issues/987). Upgrading Ransack to 2.1.1 seems to fix this, but this plugin explicitly pins the Ransack version to `< 2.1`.

Is there any reason why this couldn't be bumped to `< 2.2`?

**Comment by shioyama** [comment]
Hmm... don't remember exactly but in 6b5b3fe2 I added the upper bound to fix failing specs. Can you make a PR bumping the dependency, and we'll see if specs pass? If so I can quickly merge + release.

**Comment by shioyama** [comment]
Fixed in #6, thanks!
